apiVersion: v1
kind: Service
metadata:
  name: storage-app-ui
  labels:
    app: storage-app-ui
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30003
  selector:
    app : storage-system-ui