apiVersion: v1
kind: Service
metadata:
  name: express-app
  labels:
    app: express-app
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30009
    targetPort: 8081
  selector:
    app : storage-system-express